CREATE TABLE IF NOT EXISTS `user`(
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  authorization_key VARCHAR(30) NOT NULL,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(40) NOT NULL,
  last_connection TIMESTAMP,
  create_user TIMESTAMP NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXIST `permission`(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
    keycode VARCHAR(20) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `weather`(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    condition VARCHAR(36) NOT NULL,
    temp_c FLOAT,
    temp_f FLOAT
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `country`(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    country VARCHAR(36) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `work_pending`(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    note VARCHAR(255),
    condition BOOLEAN
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `work_complete`(
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    note VARCHAR(255)
)ENGINE=INNODB DEFAULT CHARSET=utf8;